# tutorial
https://www.tensorflow.org/tutorials/quickstart/advanced?hl=ko

below is novice version

version check

In [28]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.13.1


mnist included in tensorflow lib

In [29]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


nn model build.
flatten = flattens the input(? -> 1D)
dense = fully connected nn
dropout

In [30]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


get first elements of array and input of model

In [31]:
predictions = model(x_train[:1]).numpy()
predictions


array([[0.11182177, 0.08494323, 0.05842146, 0.10166629, 0.13635501,
        0.10085087, 0.09775245, 0.08833391, 0.08593985, 0.13391517]],
      dtype=float32)

softmax is activation function for mulit class classification
softmax will convert result into probability

In [32]:
tf.nn.softmax(predictions).numpy()


array([[0.10116434, 0.09848142, 0.09590384, 0.10014217, 0.10367693,
        0.10006054, 0.099751  , 0.0988159 , 0.09857961, 0.10342428]],
      dtype=float32)

calculate crossentropy loss using softmax => calculate difference between model prediction and actual label of input data
initial value may results about 2.3

In [40]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()


define optimizer and loss function 

In [35]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


fit method to train

In [36]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 2s 892us/step - loss: 0.2913 - accuracy: 0.9151
Epoch 2/5
1875/1875 [==============================] - 2s 887us/step - loss: 0.1413 - accuracy: 0.9586
Epoch 3/5
1875/1875 [==============================] - 2s 902us/step - loss: 0.1032 - accuracy: 0.9692
Epoch 4/5
1875/1875 [==============================] - 2s 898us/step - loss: 0.0853 - accuracy: 0.9738
Epoch 5/5
1875/1875 [==============================] - 2s 900us/step - loss: 0.0709 - accuracy: 0.9776


evaluate method to evalute trained model
evaluate method returns 'loss' and 'accuracy'

In [37]:
model.fit(x_train, y_train, epochs=5)

model.evaluate(x_test,  y_test, verbose=2)


Epoch 1/5
1875/1875 [==============================] - 2s 908us/step - loss: 0.0639 - accuracy: 0.9795
Epoch 2/5
1875/1875 [==============================] - 2s 918us/step - loss: 0.0557 - accuracy: 0.9820
Epoch 3/5
1875/1875 [==============================] - 2s 896us/step - loss: 0.0508 - accuracy: 0.9837
Epoch 4/5
1875/1875 [==============================] - 2s 915us/step - loss: 0.0470 - accuracy: 0.9848
Epoch 5/5
1875/1875 [==============================] - 2s 912us/step - loss: 0.0423 - accuracy: 0.9867
313/313 - 0s - loss: 0.0634 - accuracy: 0.9813 - 207ms/epoch - 660us/step


[0.0634298175573349, 0.9812999963760376]

define model with softmax layer as probaility model

In [38]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


can repeat upper code repeating 'probability_model'

In [41]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.08533692, 0.08533692, 0.08533692, 0.08533812, 0.08533692,
        0.08533692, 0.08533692, 0.2319665 , 0.08533692, 0.08533692],
       [0.08533676, 0.08533686, 0.23196909, 0.08533676, 0.08533676,
        0.08533676, 0.08533676, 0.08533676, 0.08533676, 0.08533676],
       [0.08533883, 0.23193625, 0.08534002, 0.08533889, 0.08533897,
        0.08533888, 0.08533925, 0.08534943, 0.0853406 , 0.08533884],
       [0.23196195, 0.08533721, 0.0853392 , 0.08533721, 0.08533723,
        0.08533721, 0.08533795, 0.08533756, 0.08533721, 0.08533725],
       [0.08534516, 0.08534516, 0.08534518, 0.08534516, 0.23183605,
        0.08534516, 0.08534516, 0.08534522, 0.08534516, 0.08540256]],
      dtype=float32)>